export const colors = {
  background: "#EEF8FB",
  backgroundWarm: "#F7F1E6",
  surface: "#FFFCF6",
  surfaceMuted: "#F4F7F5",
  surfaceElevated: "#FFFFFF",
  text: "#17213B",
  textMuted: "#6B7584",
  border: "#D6E4EA",
  borderStrong: "#BED2DB",
  primary: "#30245F",
  primaryMuted: "#E6E0FF",
  accent: "#7B6BC8",
  accentMuted: "#EFEAFF",
  coral: "#D9857B",
  coralMuted: "#F8DFD8",
  danger: "#C85C5C",
  dangerMuted: "#F8DEDE",
  success: "#3B9D70",
  successMuted: "#DDF3E8",
  nutrition: "#D76D6D",
  workout: "#4EBC7B",
  shadow: "rgba(48, 36, 95, 0.12)",
} as const;

export type ColorName = keyof typeof colors;
