/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        overload: {
          background: "#EEF8FB",
          "background-warm": "#F7F1E6",
          "calendar-grid-border": "#D6E4EA",
          "calendar-outside-surface": "#F4F7F5",
          "calendar-surface": "#FFFFFF",
          border: "#D6E4EA",
          "border-strong": "#BED2DB",
          coral: "#D9857B",
          "coral-muted": "#F8DFD8",
          cream: "#FFF9EF",
          indigo: "#30245F",
          lavender: "#DCD5FF",
          muted: "#6B7584",
          navy: "#17213B",
          nutrition: "#D76D6D",
          primary: "#30245F",
          "primary-muted": "#E6E0FF",
          sky: "#DDF2F8",
          surface: "#FFFCF6",
          "surface-elevated": "#FFFFFF",
          "surface-muted": "#F4F7F5",
          violet: "#7B6BC8",
          workout: "#4EBC7B",
        },
        "overload-dark": {
          background: "#121927",
          "background-warm": "#191A25",
          "calendar-grid-border": "#435069",
          "calendar-outside-surface": "#1C2638",
          "calendar-surface": "#222E44",
          border: "#364356",
          "border-strong": "#5A6677",
          coral: "#D9948B",
          "coral-muted": "#3B2D2D",
          danger: "#D77878",
          "danger-muted": "#3D272C",
          "hero-background": "#212C41",
          muted: "#C7D0DE",
          navy: "#F7F2E8",
          nutrition: "#D28A8A",
          primary: "#6257C6",
          "primary-muted": "#DCD7FF",
          surface: "#1A2434",
          "surface-elevated": "#253248",
          "surface-muted": "#202B3A",
          violet: "#9A91E2",
          workout: "#82C79A",
        },
      },
      borderRadius: {
        "4xl": "2rem",
      },
      boxShadow: {
        soft: "0 18px 45px rgba(48, 36, 95, 0.12)",
      },
    },
  },
  plugins: [],
};
